version: '3.1'

services:

    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: "zabbix"
            MYSQL_USER: "zabbix"
            MYSQL_PASSWORD: "zabbix_pwd"
            MYSQL_ROOT_PASSWORD: "root_pwd"
        privileged: true
        volumes:
            - /etc/docker/data/zabbix/mysql/my.cnf:/etc/mysql/my.cnf
            - /etc/docker/data/zabbix/mysql/db:/var/lib/mysql
        command:
            --character-set-server=utf8
            --collation-server=utf8_bin
            --default-authentication-plugin=mysql_native_password

    gateway:
        image: zabbix/zabbix-java-gateway:alpine-5.0-latest
        restart: always
        ports:
           - 10052:10052

    zabbix-server-mysql:
        image: zabbix/zabbix-server-mysql:alpine-5.0-latest
        environment:
            DB_SERVER_HOST: "db"
            MYSQL_DATABASE: "zabbix"
            MYSQL_USER: "zabbix"
            MYSQL_PASSWORD: "zabbix_pwd"
            MYSQL_ROOT_PASSWORD: "root_pwd"
            ZBX_JAVAGATEWAY: "zabbix-java-gateway"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /etc/docker/data/zabbix/zabbix-server-mysql/zabbix:/etc/zabbix
            - /etc/docker/data/zabbix/zabbix-server-mysql/log:/var/log
        links:
            - db:mysql
            - gateway:zabbix-java-gateway
        ports:
            - 10051:10051

    zabbix-web-nginx-mysql:
        image: zabbix/zabbix-web-nginx-mysql:alpine-5.0-latest
        restart: always
        environment:
           ZBX_SERVER_HOST: "zabbix-server-mysql"
           DB_SERVER_HOST: "db"
           MYSQL_DATABASE: "zabbix"
           MYSQL_USER: "zabbix"
           MYSQL_PASSWORD: "zabbix_pwd"
           MYSQL_ROOT_PASSWORD: "root_pwd"
           PHP_TZ: "Asia/Tokyo"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /etc/docker/data/zabbix/zabbix-web-nginx-mysql/zabbix:/etc/zabbix
            - /etc/docker/data/zabbix/zabbix-web-nginx-mysql/log:/var/log
            - /etc/docker/data/zabbix/zabbix-web-nginx-mysql/share:/usr/share/zabbix
        links:
            - db:mysql
            - zabbix-server-mysql:zabbix-server
        ports:
            - 80:8080
    zabbix-agent:
        image: zabbix/zabbix-agent:alpine-5.0-latest
        environment:
                - ZBX_HOSTNAME=Zabbix server
                - ZBX_SERVER_HOST=172.18.0.1  #the ip of docker0
        ports:
                - 10050:10050
        links:
            - zabbix-server-mysql:zabbix-server
        volumes:
                - /etc/localtime:/etc/localtime:ro
                - /etc/timezone:/etc/timezone:ro
